import { test, expect } from '@playwright/test';
const events = page => page.evaluate(() => window.evidenceChunks.flatMap(chunk => JSON.parse(chunk.events)));
test.beforeEach(async ({page}) => {
  await page.route('**/*', route => ['127.0.0.1','localhost','fonts.googleapis.com','fonts.gstatic.com'].includes(new URL(route.request().url()).hostname) ? route.continue() : route.abort());
});
test('evidence is opt-in and instruction exits are not attempts', async ({page}) => {
  await page.goto('/tests/interface/index.html?game=motor-target');
  await page.getByRole('button', {name:'Empezar a jugar'}).click();
  await page.locator('.motor-target-circle').click();
  expect(await events(page)).toEqual([]);
  await page.goto('/tests/interface/index.html?game=motor-target&evidence');
  await page.getByRole('button', {name:'Volver', exact:true}).click();
  expect(await events(page)).toEqual([]);
});
test('target evidence captures responses, completion and a separate repeated attempt', async ({page}) => {
  await page.goto('/tests/interface/index.html?game=motor-target&evidence');
  await page.getByRole('button', {name:'Empezar a jugar'}).click();
  const count = Number(await page.getByRole('progressbar').getAttribute('aria-valuemax'));
  for (let i = 0; i < count; i++) await page.locator('.motor-target-circle').click();
  await expect(page.getByRole('button', {name:'Repetir',exact:true})).toBeVisible();
  const first = await events(page);
  expect(first.filter(e => e.kind === 'start')).toHaveLength(1);
  expect(first.filter(e => e.kind === 'response')).toHaveLength(count);
  expect(first.filter(e => e.kind === 'response').every(e => e.correct && e.latencyMs >= 0)).toBe(true);
  expect(first.filter(e => e.kind === 'finish')).toHaveLength(1);
  expect(first.map(e => e.sequence)).toEqual(first.map((_, i) => i));
  await page.getByRole('button', {name:'Repetir',exact:true}).click();
  await page.locator('.motor-target-circle').click();
  await page.getByRole('button', {name:'Volver',exact:true}).click();
  const all = await events(page);
  expect(all.filter(e => e.kind === 'start')).toHaveLength(2);
  expect(all.filter(e => e.kind === 'finish')).toHaveLength(1);
  expect(all.filter(e => e.kind === 'abandon')).toMatchObject([{reason:'back'}]);
  expect(await page.evaluate(() => new Set(window.evidenceChunks.map(c => c.sessionId)).size)).toBe(2);
});
test('memory previews are excluded and a repeated sequence records help and cancellation', async ({page}) => {
  test.setTimeout(60000);
  await page.clock.install();
  await page.goto('/tests/interface/index.html?game=memory-path&evidence');
  await page.getByRole('button', {name:'Empezar a jugar'}).click();
  expect((await events(page)).filter(e => e.kind === 'stimulus')).toHaveLength(0);
  await page.getByRole('button', {name:'Comenzar',exact:true}).click();
  await page.clock.runFor(4400);
  const first = (await events(page)).filter(e => e.kind === 'stimulus');
  expect(first).toHaveLength(1);
  await page.getByRole('button', {name:'Repetir',exact:true}).click();
  expect((await events(page)).filter(e => e.kind === 'hint')).toHaveLength(1);
  expect((await events(page)).filter(e => e.kind === 'cancel')).toHaveLength(1);
  await page.clock.runFor(4400);
  await page.locator('.memory-tile').first().click();
  const recorded = await events(page);
  const response = recorded.find(e => e.kind === 'response');
  const stimulus = recorded.find(e => e.kind === 'stimulus' && e.stimulus === response.stimulus);
  expect(response.latencyMs).toBe(response.activeMs - stimulus.activeMs);
  expect(response.stimulus).toContain('replay-1');
  expect(response.latencyMs).toBeLessThan(3000);
});
test('pairs record first-card latency separately from the pair outcome', async ({page}) => {
  await page.clock.install();
  await page.goto('/tests/interface/index.html?game=memory-pairs&evidence');
  await page.getByRole('button', {name:'Empezar a jugar'}).click();
  await page.getByRole('button', {name:'Comenzar',exact:true}).click();
  await page.clock.runFor(1000);
  if (await page.getByRole('button', {name:/Ocultar/}).count()) await page.getByRole('button', {name:/Ocultar/}).click();
  await page.locator('.memory-card-tile').nth(0).click();
  let recorded = await events(page);
  expect(recorded.filter(e => e.kind === 'selection')).toHaveLength(1);
  expect(recorded.filter(e => e.kind === 'response')).toHaveLength(0);
  await page.clock.runFor(250);
  await page.locator('.memory-card-tile').nth(1).click();
  recorded = await events(page);
  expect(recorded.filter(e => e.kind === 'response')).toHaveLength(1);
  expect(recorded.find(e => e.kind === 'response').latencyMs).toBeGreaterThanOrEqual(240);
});
test('tracking records actual contact windows and flushes the final partial window on back', async ({page}) => {
  await page.clock.install();
  await page.goto('/tests/interface/index.html?game=motor-tracking&evidence');
  await page.getByRole('button', {name:'Empezar a jugar'}).click();
  await page.clock.runFor(1000);
  await page.locator('.tracking-target').focus();
  await page.keyboard.down('Space');
  await page.clock.runFor(1300);
  await page.keyboard.up('Space');
  await page.getByRole('button', {name:'Volver',exact:true}).click();
  const recorded = await events(page);
  const windows = recorded.filter(e => e.kind === 'tracking');
  expect(windows.length).toBeGreaterThanOrEqual(3);
  const duration = windows.reduce((sum,e) => sum + e.durationMs,0);
  const contact = windows.reduce((sum,e) => sum + e.contactMs,0);
  expect(duration).toBeGreaterThanOrEqual(2200);
  expect(contact).toBeGreaterThanOrEqual(1200);
  expect(contact).toBeLessThan(1400);
  expect(recorded.at(-1).kind).toBe('abandon');
  expect(recorded.filter(e => e.kind === 'response')).toHaveLength(0);
});
test('four-channel evidence requires recording and never repeats a stale frame', async ({page}) => {
  test.setTimeout(60000);
  await page.clock.install();
  await page.goto('/tests/interface/index.html?game=motor-target&evidence');
  await page.getByRole('button', {name:'Empezar a jugar'}).click();
  await page.evaluate(async () => {
    const eegService = window.eegTestService;
    const {museFeatureFrame} = await import('/src/services/museFeatures.ts');
    window.eegTestFrame = museFeatureFrame(0, [5,10,20,35].map(hz => Array.from({length:256}, (_,i) => 20*Math.sin(2*Math.PI*hz*i/256))));
    eegService.install({id:'test-four-channel', supported:()=>true, metric:{id:'test',label:'Prueba',unit:'µV',min:0,max:100},
      async connect(events) { window.eegTestEvents=events; return {disconnect(){}}; }});
    await eegService.connect(false);
    window.eegTestEvents.channels(window.eegTestFrame);
  });
  await page.clock.runFor(1100);
  expect((await events(page)).filter(e => e.kind === 'eeg')).toHaveLength(0);
  await page.evaluate(async () => {
    const eegService = window.eegTestService;
    eegService.disconnect(); await eegService.connect(true);
    window.eegTestEvents.channels(window.eegTestFrame);
  });
  await page.clock.runFor(1100);
  const frames = (await events(page)).filter(e => e.kind === 'eeg');
  expect(frames).toHaveLength(1);
  expect(frames[0].frame.channels.map(c => c.channel)).toEqual(['TP9','AF7','AF8','TP10']);
  await page.clock.runFor(1100);
  expect((await events(page)).filter(e => e.kind === 'eeg')).toHaveLength(1);
  await page.evaluate(() => window.eegTestService.disconnect());
  await page.clock.runFor(1100);
  expect((await events(page)).filter(e => e.kind === 'eeg')).toHaveLength(1);
});
